version: "3"

services:
  main_db:
    image: "postgres:latest"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main_db
    volumes:
      - ./db-data/main_db/:/var/lib/postgresql/data/


volumes:
  main_db_volume: